services:
  kaair_container:
    image: kaair:humble-cpu  # 빌드한 이미지 이름
    container_name: keti_ros2_container
    network_mode: host           # ROS 2 통신을 위해 host 모드 권장
    ipc: host                    # FastDDS 공유 메모리 통신을 위해 필요
    privileged: true             # GPU 및 하드웨어 접근 권한
    restart: unless-stopped
    #user: root                  # host id가 아닌 sudo id 생성시 주석 제거. 기본 id 1000


    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-30}         # 원하는 ID로 변경 가능
      # Fast DDS, Cyclone DDS를 선택해서 주석처리. moveit은 cyclone dds 사용 추천
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///ros_ws/cyclonedds.xml
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # - FASTRTPS_DEFAULT_PROFILES_FILE=/ros_ws/fastdds_profile.xml
      # - RMW_FASTRTPS_USE_QOS_FROM_XML=1
    
    volumes:
      # GUI 설정을 위한 X11 소켓 매핑
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # USB, 카메라 장치 매핑
      - /dev:/dev
      - /dev/shm:/dev/shm # 3. 추가: FastDDS 공유 메모리 성능 최적화
      # 프로젝트 폴더 매핑 (호스트의 현재 디렉토리를 컨테이너의 /ros_ws로)
      - .:/ros_ws

      #  Jetpack 7(Thor)의 드라이버 경로들을 더 포괄적으로 매핑
      # - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
      # - /usr/lib/aarch64-linux-gnu/dri:/usr/lib/aarch64-linux-gnu/dri
      # - /usr/share/glvnd:/usr/share/glvnd

    # 일반 유저 실행 시 권한 문제 해결의 핵심
    group_add:
      - video
      - plugdev
      - sudo  # 필요시 추가
      - dialout  # 추가: 시리얼 포트 접근 권한


    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /ros_ws
    command: >
      bash -c "pip install -r requirements.txt && /bin/bash"