
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  head_joint1:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  head_joint2:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  joint1:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  joint2:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  joint3:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  joint4:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  joint5:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  joint6:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  joint7:
    has_velocity_limits: true
    max_velocity: 2.14
    has_acceleration_limits: true
    max_acceleration: 3.1
  lift_joint:
    has_velocity_limits: true
    max_velocity: 0.20000000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  virtual_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0