# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 1.0
  execution_duration_monitoring: true
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm7_traj_controller
    - lift_controller

  xarm7_traj_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    action_ns: follow_joint_trajectory
    default: True
  lift_controller:
    type: FollowJointTrajectory
    joints:
      - lift_joint
    action_ns: follow_joint_trajectory
    default: True