string object_label
int32[] u_array
int32[] v_array
float64[] d_array
string base_frame
---
bool success
string message
float64[] x_array
float64[] y_array
float64[] z_array
float64[] depth_raw_array
uint8[] r_array
uint8[] g_array
uint8[] b_array
